planet:
  mysql:
    ip: localhost # 服务器ip
    port: 3306
    db: changli-planet # database名
    username: root
    password: CreaMaker1@
  redis:
    host: localhost
    port: 6379
    password: 1234