planet:
  mysql:
    ip: localhost # 服务器ip
    port: 3306
    db: csust_planet # database名
    username: root
    password: 3232539921
  redis:
    host: localhost
    port: 6379
    password: 3232539921
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin